name: CD - Build, Push, and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./payoneer
          push: true
          tags: santichuit/pnr:${{ github.ref_name }}


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/pnr:${{ github.ref_name }}
            echo "$(date) - Pulled version ${{ github.ref_name }}" >> /tmp/deployment.log
            docker stop payoneer-container || true
            docker rm payoneer-container || true
            docker run -d --name payoneer-container -p 80:4200 ${{ secrets.DOCKER_USERNAME }}/pnr:${{ github.ref_name }}
            echo "Deployment completed at $(date)" >> /tmp/deployment.log


