name: CD - Build, Push, and Deploy

on:
  pull_request:
    types:
      - closed
    branches:
      - master
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      rollback_tag:
        description: 'Tag to rollback to (leave empty for latest deployment)'
        required: false


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{ github.event.inputs.rollback_tag }}" ]; then
            echo "DEPLOY_TAG=${{ github.event.inputs.rollback_tag }}" >> $GITHUB_ENV   # Manual rollback via UI
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "DEPLOY_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV                  # Tag push via git
          else
            echo "DEPLOY_TAG=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_ENV               # PR Merge
          fi

      - name: Create and push tag    # Creates a tag for a merged PR
        if: github.event_name == 'pull_request'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag ${{ env.DEPLOY_TAG }}
          git push origin ${{ env.DEPLOY_TAG }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./payoneer
          push: true
          tags: santichuit/pnr:${{ env.DEPLOY_TAG }}


      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/pnr:${{ env.DEPLOY_TAG }}
            echo "$(date) - Pulled version ${{ env.DEPLOY_TAG }}" >> /tmp/deployment.log
            docker stop payoneer-container || true
            docker rm payoneer-container || true
            docker run -d --name payoneer-container -p 80:4200 ${{ secrets.DOCKER_USERNAME }}/pnr:${{ env.DEPLOY_TAG }}
            echo "Deployment completed at $(date)" >> /tmp/deployment.log


